#!/bin/sh

wordlist=/usr/share/diction/word-list.txt
contador=1
separador='-'
entropia=si
words=6

unica_tirada() {
  tirada=$(shuf -r -z -i 1-6 -n 5)
  grep "^$tirada" $wordlist 2>/dev/null \
    || shuf -n1 $wordlist
}

ayuda() {
  cat <<EOF
  -n    <numero>  para numero de palabras 
  -s    <caracter> para cambiar separador entre palabras
  -d    </ruta/a/la/lista> usar otro diccionario
  -q    menos verbosidad solo imprime la contraseña
EOF
}

frase_de_paso() {
  for i in $(seq $words); do
    unica_tirada | awk '{print $NF}'
  done | tr '\n' "$separador"
}

while getopts 'qs:e:d:n:' OPT; do
  case $OPT in
    s) separador=$OPTARG;;
    n) words=$OPTARG;;
    d) wordlist=$OPTARG;;
    q) entropia=no;;
    e) en=$OPTARG;;
    *) ayuda; exit;;
  esac
done
shift $((OPTIND - 1))

[ -e "$wordlist" ] \
  || { echo 'no existe diccionario, especifica uno con el parametro d'; exit 1; }

rm_last=$(frase_de_paso)
contra=${rm_last%?}

entropia () {
  palabras=$(wc -l < $wordlist)
  printf '%s\n' "de un diccionario con $palabras palabras"
  entropia=$(echo "scale=2; l($palabras)/l(2)" | bc -l)
  printf 'entropia '
  printf '%s\n' "$entropia * $words" | bc -l
  printf '%s\n' "longitud $(echo -n $contra | wc -c)"
}

mensaje_nivel_entropia() {
  level="$(printf '%s\n' "scale=1; 12.9 * $words" | bc -l | cut -d'.' -f1)" 
  if [ "$level" -lt 65 ]; then
    printf "\033[1;35m%s \033[1;35m%s\033[0m\n" "contraseña debil"
  elif [ "$level" -lt 100 ]; then
    printf "\033[1;33m\033[1;33m%s\033[1;33m \033[1;33m%s\033[0m\n" "contraseña buena"
  else
    printf "\033[0;32m%s\033[0m\n" "contraseña muy buena"
  fi
}
 
[ $entropia = si ] && mensaje_nivel_entropia && entropia
echo "$contra"
