#!/bin/sh

#'123456'
wordlist="/usr/share/diction/word-list"
contador=1
separador='-'
entropia=si

words=6
#words=$(shuf -z -n 1 -i 6-10)
combinacion() {
  place=$(shuf -z -i 1-5)
#  cam=$(head -1 wo | wc -w)
  grep "^$place" $wordlist 2>/dev/null \
    || shuf -n 1 $wordlist 2>/dev/null
}

ayuda() {
  cat << EOF
  -n    <numero>  para numero de palabras 
  -s    <caracter> para cambiar separador entre palabras
  -d    </ruta/a/la/lista> usar otro diccionario
  -q    menos verbosidad solo imprime la contraseña
  -e    para comprobar entropia de contraseña (no imprementado)
EOF
}

string() {
for i in $(seq 1 $words); do
  combinacion | awk '{print $2}'
done | tr '\n' "$separador"
}

while getopts 'qs:e:d:n:' OPT; do
  case $OPT in
    s) separador=$OPTARG;;
    n) words=$OPTARG;;
    d) wordlist=$OPTARG;;
    q) entropia=no;;
    e) en=$OPTARG;;
    *) ayuda; exit;;
  esac
done
shift $((OPTIND - 1))

[ -e "$wordlist" ] \
  || { echo "no existe $wordlist, especifica uno con el parametro d"; exit; }

contra=$(string)

entropia () {
#  wor=$(wc -l < $wordlist)
#  wor=$(echo $en | wc -c)
#  echo "scale=2; l(26)/l(2)" | bc -l
  printf 'entropia '
  printf '%s\n' "12.9 * $words" | bc -l
  printf '%s\n' "longitud $(echo -n $contra | wc -c)"
}

mensaje_nivel_entropia() {
level="$(printf '%s\n' "12.9 * $words" | bc -l | cut -d'.' -f1)" 
if [ "$level" -lt 65 ]; then
  printf "\033[1;35m%s \033[1;35m%s\033[0m\n" "contraseña debil"
elif [ "$level" -lt 100 ]; then
  printf "\033[1;33m\033[1;33m%s\033[1;33m \033[1;33m%s\033[0m\n" "contraseña buena"
else
  printf "\033[0;32m%s\033[0m\n" "contraseña muy buena"
fi
}

entropia_de_entrada () {
resultado=$(string)
# 26 posibilidades no alfabeto derivado do latin insensible a caixa
set_caracteres=26

# grupos de caracteres
latino=$(echo $en | grep -Eo '[a-z]' | wc -l)
numeros_arabigos=$(echo $en | grep -Eo '[0-9]' | wc -l)
capitales=$(echo $en | grep -Eo '[A-Z]' | wc -l)
especiales=$(echo $en | grep -Eo '[&$%.,]' | wc -l)

#numero_caracteres_da_contra
longitud=$(echo $resultado | wc -c)
echo $longitud

posibles_combinacions=$(echo "$set_caracteres ^ $longitud" | bc -l)

#algoritmo en base 2
echo "scale=2; l($posibles_combinacions)/l(2)" | bc -l
}

[ $entropia = si ] && mensaje_nivel_entropia && entropia
echo "$contra"
#string
